# Generated by Django 6.0.2 on 2026-03-05 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('college', 'College Bus'), ('tourist', 'Tourist Bus')], default='college', max_length=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(default=49),
        ),
        migrations.CreateModel(
            name='BusCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('boarding_point', models.CharField(blank=True, max_length=200)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='core.bus')),
            ],
        ),
    ]
