# Generated by Django 6.0.2 on 2026-03-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bus_bus_type_alter_bus_capacity_buscoordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('fare', models.PositiveIntegerField(default=0, help_text='Bus fare in INR – must be rounded to nearest 10 (e.g. 50, 60, 110)')),
            ],
            options={
                'ordering': ['fare', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='buspass',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0, help_text='Fare in INR rounded to nearest 10'),
        ),
        migrations.AddField(
            model_name='buspass',
            name='boarding_point_ref',
            field=models.ForeignKey(blank=True, help_text='Link to fare table entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_passes', to='core.boardingpoint'),
        ),
    ]
