# Generated by Django 6.0.2 on 2026-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_boardingpoint_alter_buspass_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspass',
            name='notes',
            field=models.CharField(blank=True, default='', help_text="Extra label, e.g. 'Faculty Reserve – Dr. John'", max_length=300),
        ),
    ]
