# Generated by Django 6.0.2 on 2026-03-13 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_buspass_notes_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver user account assigned to this bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bus',
            name='is_tracking',
            field=models.BooleanField(default=False, help_text='True while driver is sharing location'),
        ),
        migrations.AddField(
            model_name='bus',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('driver', 'Driver'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
