# Generated by Django 6.0.2 on 2026-03-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bus_driver_bus_is_tracking_bus_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_type',
            field=models.CharField(choices=[('day_scholar', 'Day Scholar'), ('hosteler', 'Hosteler')], default='hosteler', help_text='Day Scholar: free QR attendance only. Hosteler: must book & pay for pass.', max_length=15),
        ),
    ]
