# Generated by Django 6.0.2 on 2026-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspass',
            name='payment_notes',
            field=models.CharField(blank=True, default='', help_text='UPI transaction ID or extra payment notes from student', max_length=200),
        ),
        migrations.AddField(
            model_name='buspass',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='UPI payment screenshot uploaded by student as proof', null=True, upload_to='payment_proofs/'),
        ),
    ]
